/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package serializers.thrift;


public class Size {
  public static final int SMALL = 1;
  public static final int LARGE = 2;
}
