#! /usr/bin/env bash
set -e

path_sep=":"
case "`uname`" in
	CYGWIN*) path_sep=";" ;;
esac

cp=build/bytecode/main$path_sep$(cat build/lib-core-cp)
loaderClasspath=build/bytecode/main/sx$path_sep$(cat build/lib-cp)$path_sep$(cat build/gen-cp)
exec java -Dgemfire.AutoSerializer.SAFE=true -Xmx16m -server -cp "$cp" -Dloader.classpath=${loaderClasspath} core.BenchmarkRunner "$@"

# Values used during testing are small.  Should probably use fairly
# small heap to capture effects of memory allocation
