#! /usr/bin/env bash
set -e
cp=build/bytecode/main:$(cat build/gen-cp):$(cat build/lib-cp)
exec java -Xmx16m -server -cp "$cp" serializers.BenchmarkRunner "$@"

# Values used during testing are small.  Should probably use fairly
# small heap to capture effects of memory allocation
