#! /usr/bin/env bash

# SIMPLE/GENERIC: Serializes any POJO without special knowledge about the class.
./run -trials=500 -chart -include=java-built-in,hessian,kryo,protostuff-runtime,msgpack,json/jackson/databind,json/jackson/databind-strings,json/jackson/db-afterburner,json/google-gson/databind,json/svenson-databind*,json/flexjson/databind,json/fastjson/databind,smile/jackson/databind,smile/jackson/db-afterburner,smile/protostuff-runtime,bson/jackson/databind,xml/xstream+c,xml/jackson/databind-aalto,json/protostuff-runtime data/media.1.cks

# SIMPLE/SPECIFC: Serializes only specific classes using code generation or other special knowledge about the class.
./run -trials=500 -chart -include=wobly,wobly-compact,kryo-opt,protobuf,protobuf/activemq+alt*,protostuff,protobuf/protostuff,thrift,thrift-compact,avro,json/json-lib-databind,json/jsonij-jpath,json/jsonpath/json.simple data/media.1.cks

# MANUAL: Serializes only specific classes using hand written serialization code.
./run -trials=500 -chart -include=java-manual,kryo-manual,protostuff-manual,msgpack-manual,json/jackson/manual,json/jackson/tree,json/jackson/tree-strings,json/protostuff-manual,json/google-gson/manual,json/google-gson/manual/tree,json/json.simple/manual,json/json.simple/manual/tree,json/json-smart/manual/tree,json/org.json/manual/tree,json/jsonij-manual/tree,json/argo-manual/tree,smile/jackson/manual,smile/protostuff-manual,bson/mongodb,xml/woodstox-manual,xml/aalto-manual,xml/fastinfo-manual,xml/xstream+c-woodstox,xml/xstream+c-aalto,xml/xstream+c-fastinfo,xml/javolution,avro-generic data/media.1.cks
