// Generated by the protocol buffer compiler.  DO NOT EDIT!

package serializers.protobuf;

public final class MediaContentHolder {
  private MediaContentHolder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Image extends
      com.google.protobuf.GeneratedMessage {
    // Use Image.newBuilder() to construct.
    private Image() {}
    
    private static final Image defaultInstance = new Image();
    public static Image getDefaultInstance() {
      return defaultInstance;
    }
    
    public Image getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return serializers.protobuf.MediaContentHolder.internal_static_serializers_protobuf_Image_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return serializers.protobuf.MediaContentHolder.internal_static_serializers_protobuf_Image_fieldAccessorTable;
    }
    
    public static enum Size {
      SMALL(0, 0),
      LARGE(1, 1),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static Size valueOf(int value) {
        switch (value) {
          case 0: return SMALL;
          case 1: return LARGE;
          default: return null;
        }
      }
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return serializers.protobuf.MediaContentHolder.Image.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Size[] VALUES = {
        SMALL, LARGE, 
      };
      public static Size valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private Size(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        serializers.protobuf.MediaContentHolder.getDescriptor();
      }
    }
    
    // required string uri = 1;
    private boolean hasUri;
    private java.lang.String uri_ = "";
    public boolean hasUri() { return hasUri; }
    public java.lang.String getUri() { return uri_; }
    
    // optional string title = 2;
    private boolean hasTitle;
    private java.lang.String title_ = "";
    public boolean hasTitle() { return hasTitle; }
    public java.lang.String getTitle() { return title_; }
    
    // optional int32 width = 3;
    private boolean hasWidth;
    private int width_ = 0;
    public boolean hasWidth() { return hasWidth; }
    public int getWidth() { return width_; }
    
    // optional int32 height = 4;
    private boolean hasHeight;
    private int height_ = 0;
    public boolean hasHeight() { return hasHeight; }
    public int getHeight() { return height_; }
    
    // optional .serializers.protobuf.Image.Size size = 5;
    private boolean hasSize;
    private serializers.protobuf.MediaContentHolder.Image.Size size_ = serializers.protobuf.MediaContentHolder.Image.Size.SMALL;
    public boolean hasSize() { return hasSize; }
    public serializers.protobuf.MediaContentHolder.Image.Size getSize() { return size_; }
    
    public static serializers.protobuf.MediaContentHolder.Image parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.Image parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.Image parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.Image parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.Image parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.Image parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.Image parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.Image parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(serializers.protobuf.MediaContentHolder.Image prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using serializers.protobuf.MediaContentHolder.Image.newBuilder()
      private Builder() {}
      
      serializers.protobuf.MediaContentHolder.Image result = new serializers.protobuf.MediaContentHolder.Image();
      
      @Override
      protected serializers.protobuf.MediaContentHolder.Image internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new serializers.protobuf.MediaContentHolder.Image();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return serializers.protobuf.MediaContentHolder.Image.getDescriptor();
      }
      
      public serializers.protobuf.MediaContentHolder.Image getDefaultInstanceForType() {
        return serializers.protobuf.MediaContentHolder.Image.getDefaultInstance();
      }
      
      public serializers.protobuf.MediaContentHolder.Image build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private serializers.protobuf.MediaContentHolder.Image buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public serializers.protobuf.MediaContentHolder.Image buildPartial() {
        serializers.protobuf.MediaContentHolder.Image returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string uri = 1;
      public boolean hasUri() {
        return result.hasUri();
      }
      public java.lang.String getUri() {
        return result.getUri();
      }
      public Builder setUri(java.lang.String value) {
        result.hasUri = true;
        result.uri_ = value;
        return this;
      }
      public Builder clearUri() {
        result.hasUri = false;
        result.uri_ = "";
        return this;
      }
      
      // optional string title = 2;
      public boolean hasTitle() {
        return result.hasTitle();
      }
      public java.lang.String getTitle() {
        return result.getTitle();
      }
      public Builder setTitle(java.lang.String value) {
        result.hasTitle = true;
        result.title_ = value;
        return this;
      }
      public Builder clearTitle() {
        result.hasTitle = false;
        result.title_ = "";
        return this;
      }
      
      // optional int32 width = 3;
      public boolean hasWidth() {
        return result.hasWidth();
      }
      public int getWidth() {
        return result.getWidth();
      }
      public Builder setWidth(int value) {
        result.hasWidth = true;
        result.width_ = value;
        return this;
      }
      public Builder clearWidth() {
        result.hasWidth = false;
        result.width_ = 0;
        return this;
      }
      
      // optional int32 height = 4;
      public boolean hasHeight() {
        return result.hasHeight();
      }
      public int getHeight() {
        return result.getHeight();
      }
      public Builder setHeight(int value) {
        result.hasHeight = true;
        result.height_ = value;
        return this;
      }
      public Builder clearHeight() {
        result.hasHeight = false;
        result.height_ = 0;
        return this;
      }
      
      // optional .serializers.protobuf.Image.Size size = 5;
      public boolean hasSize() {
        return result.hasSize();
      }
      public serializers.protobuf.MediaContentHolder.Image.Size getSize() {
        return result.getSize();
      }
      public Builder setSize(serializers.protobuf.MediaContentHolder.Image.Size value) {
        result.hasSize = true;
        result.size_ = value;
        return this;
      }
      public Builder clearSize() {
        result.hasSize = false;
        result.size_ = serializers.protobuf.MediaContentHolder.Image.Size.SMALL;
        return this;
      }
    }
    
    static {
      serializers.protobuf.MediaContentHolder.getDescriptor();
    }
  }
  
  public static final class Media extends
      com.google.protobuf.GeneratedMessage {
    // Use Media.newBuilder() to construct.
    private Media() {}
    
    private static final Media defaultInstance = new Media();
    public static Media getDefaultInstance() {
      return defaultInstance;
    }
    
    public Media getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return serializers.protobuf.MediaContentHolder.internal_static_serializers_protobuf_Media_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return serializers.protobuf.MediaContentHolder.internal_static_serializers_protobuf_Media_fieldAccessorTable;
    }
    
    public static enum Player {
      JAVA(0, 0),
      ;
      
      public static final Player FLASH = JAVA;
      
      public final int getNumber() { return value; }
      
      public static Player valueOf(int value) {
        switch (value) {
          case 0: return JAVA;
          default: return null;
        }
      }
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return serializers.protobuf.MediaContentHolder.Media.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Player[] VALUES = {
        JAVA, FLASH, 
      };
      public static Player valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private Player(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        serializers.protobuf.MediaContentHolder.getDescriptor();
      }
    }
    
    // required string uri = 1;
    private boolean hasUri;
    private java.lang.String uri_ = "";
    public boolean hasUri() { return hasUri; }
    public java.lang.String getUri() { return uri_; }
    
    // optional string title = 2;
    private boolean hasTitle;
    private java.lang.String title_ = "";
    public boolean hasTitle() { return hasTitle; }
    public java.lang.String getTitle() { return title_; }
    
    // optional int32 width = 3;
    private boolean hasWidth;
    private int width_ = 0;
    public boolean hasWidth() { return hasWidth; }
    public int getWidth() { return width_; }
    
    // optional int32 height = 4;
    private boolean hasHeight;
    private int height_ = 0;
    public boolean hasHeight() { return hasHeight; }
    public int getHeight() { return height_; }
    
    // optional string format = 5;
    private boolean hasFormat;
    private java.lang.String format_ = "";
    public boolean hasFormat() { return hasFormat; }
    public java.lang.String getFormat() { return format_; }
    
    // optional int64 duration = 6;
    private boolean hasDuration;
    private long duration_ = 0L;
    public boolean hasDuration() { return hasDuration; }
    public long getDuration() { return duration_; }
    
    // optional int64 size = 7;
    private boolean hasSize;
    private long size_ = 0L;
    public boolean hasSize() { return hasSize; }
    public long getSize() { return size_; }
    
    // optional int32 bitrate = 8;
    private boolean hasBitrate;
    private int bitrate_ = 0;
    public boolean hasBitrate() { return hasBitrate; }
    public int getBitrate() { return bitrate_; }
    
    // repeated string person = 9;
    private java.util.List<java.lang.String> person_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getPersonList() {
      return person_;
    }
    public int getPersonCount() { return person_.size(); }
    public java.lang.String getPerson(int index) {
      return person_.get(index);
    }
    
    // optional .serializers.protobuf.Media.Player player = 10;
    private boolean hasPlayer;
    private serializers.protobuf.MediaContentHolder.Media.Player player_ = serializers.protobuf.MediaContentHolder.Media.Player.JAVA;
    public boolean hasPlayer() { return hasPlayer; }
    public serializers.protobuf.MediaContentHolder.Media.Player getPlayer() { return player_; }
    
    // optional string copyright = 11;
    private boolean hasCopyright;
    private java.lang.String copyright_ = "";
    public boolean hasCopyright() { return hasCopyright; }
    public java.lang.String getCopyright() { return copyright_; }
    
    public static serializers.protobuf.MediaContentHolder.Media parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.Media parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.Media parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.Media parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.Media parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.Media parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.Media parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.Media parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(serializers.protobuf.MediaContentHolder.Media prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using serializers.protobuf.MediaContentHolder.Media.newBuilder()
      private Builder() {}
      
      serializers.protobuf.MediaContentHolder.Media result = new serializers.protobuf.MediaContentHolder.Media();
      
      @Override
      protected serializers.protobuf.MediaContentHolder.Media internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new serializers.protobuf.MediaContentHolder.Media();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return serializers.protobuf.MediaContentHolder.Media.getDescriptor();
      }
      
      public serializers.protobuf.MediaContentHolder.Media getDefaultInstanceForType() {
        return serializers.protobuf.MediaContentHolder.Media.getDefaultInstance();
      }
      
      public serializers.protobuf.MediaContentHolder.Media build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private serializers.protobuf.MediaContentHolder.Media buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public serializers.protobuf.MediaContentHolder.Media buildPartial() {
        if (result.person_ != java.util.Collections.EMPTY_LIST) {
          result.person_ =
            java.util.Collections.unmodifiableList(result.person_);
        }
        serializers.protobuf.MediaContentHolder.Media returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string uri = 1;
      public boolean hasUri() {
        return result.hasUri();
      }
      public java.lang.String getUri() {
        return result.getUri();
      }
      public Builder setUri(java.lang.String value) {
        result.hasUri = true;
        result.uri_ = value;
        return this;
      }
      public Builder clearUri() {
        result.hasUri = false;
        result.uri_ = "";
        return this;
      }
      
      // optional string title = 2;
      public boolean hasTitle() {
        return result.hasTitle();
      }
      public java.lang.String getTitle() {
        return result.getTitle();
      }
      public Builder setTitle(java.lang.String value) {
        result.hasTitle = true;
        result.title_ = value;
        return this;
      }
      public Builder clearTitle() {
        result.hasTitle = false;
        result.title_ = "";
        return this;
      }
      
      // optional int32 width = 3;
      public boolean hasWidth() {
        return result.hasWidth();
      }
      public int getWidth() {
        return result.getWidth();
      }
      public Builder setWidth(int value) {
        result.hasWidth = true;
        result.width_ = value;
        return this;
      }
      public Builder clearWidth() {
        result.hasWidth = false;
        result.width_ = 0;
        return this;
      }
      
      // optional int32 height = 4;
      public boolean hasHeight() {
        return result.hasHeight();
      }
      public int getHeight() {
        return result.getHeight();
      }
      public Builder setHeight(int value) {
        result.hasHeight = true;
        result.height_ = value;
        return this;
      }
      public Builder clearHeight() {
        result.hasHeight = false;
        result.height_ = 0;
        return this;
      }
      
      // optional string format = 5;
      public boolean hasFormat() {
        return result.hasFormat();
      }
      public java.lang.String getFormat() {
        return result.getFormat();
      }
      public Builder setFormat(java.lang.String value) {
        result.hasFormat = true;
        result.format_ = value;
        return this;
      }
      public Builder clearFormat() {
        result.hasFormat = false;
        result.format_ = "";
        return this;
      }
      
      // optional int64 duration = 6;
      public boolean hasDuration() {
        return result.hasDuration();
      }
      public long getDuration() {
        return result.getDuration();
      }
      public Builder setDuration(long value) {
        result.hasDuration = true;
        result.duration_ = value;
        return this;
      }
      public Builder clearDuration() {
        result.hasDuration = false;
        result.duration_ = 0L;
        return this;
      }
      
      // optional int64 size = 7;
      public boolean hasSize() {
        return result.hasSize();
      }
      public long getSize() {
        return result.getSize();
      }
      public Builder setSize(long value) {
        result.hasSize = true;
        result.size_ = value;
        return this;
      }
      public Builder clearSize() {
        result.hasSize = false;
        result.size_ = 0L;
        return this;
      }
      
      // optional int32 bitrate = 8;
      public boolean hasBitrate() {
        return result.hasBitrate();
      }
      public int getBitrate() {
        return result.getBitrate();
      }
      public Builder setBitrate(int value) {
        result.hasBitrate = true;
        result.bitrate_ = value;
        return this;
      }
      public Builder clearBitrate() {
        result.hasBitrate = false;
        result.bitrate_ = 0;
        return this;
      }
      
      // repeated string person = 9;
      public java.util.List<java.lang.String> getPersonList() {
        return java.util.Collections.unmodifiableList(result.person_);
      }
      public int getPersonCount() {
        return result.getPersonCount();
      }
      public java.lang.String getPerson(int index) {
        return result.getPerson(index);
      }
      public Builder setPerson(int index, java.lang.String value) {
        result.person_.set(index, value);
        return this;
      }
      public Builder addPerson(java.lang.String value) {
        if (result.person_.isEmpty()) {
          result.person_ = new java.util.ArrayList<java.lang.String>();
        }
        result.person_.add(value);
        return this;
      }
      public Builder addAllPerson(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.person_.isEmpty()) {
          result.person_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.person_);
        return this;
      }
      public Builder clearPerson() {
        result.person_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional .serializers.protobuf.Media.Player player = 10;
      public boolean hasPlayer() {
        return result.hasPlayer();
      }
      public serializers.protobuf.MediaContentHolder.Media.Player getPlayer() {
        return result.getPlayer();
      }
      public Builder setPlayer(serializers.protobuf.MediaContentHolder.Media.Player value) {
        result.hasPlayer = true;
        result.player_ = value;
        return this;
      }
      public Builder clearPlayer() {
        result.hasPlayer = false;
        result.player_ = serializers.protobuf.MediaContentHolder.Media.Player.JAVA;
        return this;
      }
      
      // optional string copyright = 11;
      public boolean hasCopyright() {
        return result.hasCopyright();
      }
      public java.lang.String getCopyright() {
        return result.getCopyright();
      }
      public Builder setCopyright(java.lang.String value) {
        result.hasCopyright = true;
        result.copyright_ = value;
        return this;
      }
      public Builder clearCopyright() {
        result.hasCopyright = false;
        result.copyright_ = "";
        return this;
      }
    }
    
    static {
      serializers.protobuf.MediaContentHolder.getDescriptor();
    }
  }
  
  public static final class MediaContent extends
      com.google.protobuf.GeneratedMessage {
    // Use MediaContent.newBuilder() to construct.
    private MediaContent() {}
    
    private static final MediaContent defaultInstance = new MediaContent();
    public static MediaContent getDefaultInstance() {
      return defaultInstance;
    }
    
    public MediaContent getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return serializers.protobuf.MediaContentHolder.internal_static_serializers_protobuf_MediaContent_descriptor;
    }
    
    @Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return serializers.protobuf.MediaContentHolder.internal_static_serializers_protobuf_MediaContent_fieldAccessorTable;
    }
    
    // repeated .serializers.protobuf.Image image = 1;
    private java.util.List<serializers.protobuf.MediaContentHolder.Image> image_ =
      java.util.Collections.emptyList();
    public java.util.List<serializers.protobuf.MediaContentHolder.Image> getImageList() {
      return image_;
    }
    public int getImageCount() { return image_.size(); }
    public serializers.protobuf.MediaContentHolder.Image getImage(int index) {
      return image_.get(index);
    }
    
    // optional .serializers.protobuf.Media media = 2;
    private boolean hasMedia;
    private serializers.protobuf.MediaContentHolder.Media media_ = serializers.protobuf.MediaContentHolder.Media.getDefaultInstance();
    public boolean hasMedia() { return hasMedia; }
    public serializers.protobuf.MediaContentHolder.Media getMedia() { return media_; }
    
    public static serializers.protobuf.MediaContentHolder.MediaContent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.MediaContent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.MediaContent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.MediaContent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.MediaContent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.MediaContent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.MediaContent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static serializers.protobuf.MediaContentHolder.MediaContent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(serializers.protobuf.MediaContentHolder.MediaContent prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using serializers.protobuf.MediaContentHolder.MediaContent.newBuilder()
      private Builder() {}
      
      serializers.protobuf.MediaContentHolder.MediaContent result = new serializers.protobuf.MediaContentHolder.MediaContent();
      
      @Override
      protected serializers.protobuf.MediaContentHolder.MediaContent internalGetResult() {
        return result;
      }
      
      @Override
      public Builder clear() {
        result = new serializers.protobuf.MediaContentHolder.MediaContent();
        return this;
      }
      
      @Override
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return serializers.protobuf.MediaContentHolder.MediaContent.getDescriptor();
      }
      
      public serializers.protobuf.MediaContentHolder.MediaContent getDefaultInstanceForType() {
        return serializers.protobuf.MediaContentHolder.MediaContent.getDefaultInstance();
      }
      
      public serializers.protobuf.MediaContentHolder.MediaContent build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private serializers.protobuf.MediaContentHolder.MediaContent buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public serializers.protobuf.MediaContentHolder.MediaContent buildPartial() {
        if (result.image_ != java.util.Collections.EMPTY_LIST) {
          result.image_ =
            java.util.Collections.unmodifiableList(result.image_);
        }
        serializers.protobuf.MediaContentHolder.MediaContent returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // repeated .serializers.protobuf.Image image = 1;
      public java.util.List<serializers.protobuf.MediaContentHolder.Image> getImageList() {
        return java.util.Collections.unmodifiableList(result.image_);
      }
      public int getImageCount() {
        return result.getImageCount();
      }
      public serializers.protobuf.MediaContentHolder.Image getImage(int index) {
        return result.getImage(index);
      }
      public Builder setImage(int index, serializers.protobuf.MediaContentHolder.Image value) {
        result.image_.set(index, value);
        return this;
      }
      public Builder setImage(int index, serializers.protobuf.MediaContentHolder.Image.Builder builderForValue) {
        result.image_.set(index, builderForValue.build());
        return this;
      }
      public Builder addImage(serializers.protobuf.MediaContentHolder.Image value) {
        if (result.image_.isEmpty()) {
          result.image_ = new java.util.ArrayList<serializers.protobuf.MediaContentHolder.Image>();
        }
        result.image_.add(value);
        return this;
      }
      public Builder addImage(serializers.protobuf.MediaContentHolder.Image.Builder builderForValue) {
        if (result.image_.isEmpty()) {
          result.image_ = new java.util.ArrayList<serializers.protobuf.MediaContentHolder.Image>();
        }
        result.image_.add(builderForValue.build());
        return this;
      }
      public Builder addAllImage(
          java.lang.Iterable<? extends serializers.protobuf.MediaContentHolder.Image> values) {
        if (result.image_.isEmpty()) {
          result.image_ = new java.util.ArrayList<serializers.protobuf.MediaContentHolder.Image>();
        }
        super.addAll(values, result.image_);
        return this;
      }
      public Builder clearImage() {
        result.image_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional .serializers.protobuf.Media media = 2;
      public boolean hasMedia() {
        return result.hasMedia();
      }
      public serializers.protobuf.MediaContentHolder.Media getMedia() {
        return result.getMedia();
      }
      public Builder setMedia(serializers.protobuf.MediaContentHolder.Media value) {
        result.hasMedia = true;
        result.media_ = value;
        return this;
      }
      public Builder setMedia(serializers.protobuf.MediaContentHolder.Media.Builder builderForValue) {
        result.hasMedia = true;
        result.media_ = builderForValue.build();
        return this;
      }
      public Builder mergeMedia(serializers.protobuf.MediaContentHolder.Media value) {
        if (result.hasMedia() &&
            result.media_ != serializers.protobuf.MediaContentHolder.Media.getDefaultInstance()) {
          result.media_ =
            serializers.protobuf.MediaContentHolder.Media.newBuilder(result.media_).mergeFrom(value).buildPartial();
        } else {
          result.media_ = value;
        }
        result.hasMedia = true;
        return this;
      }
      public Builder clearMedia() {
        result.hasMedia = false;
        result.media_ = serializers.protobuf.MediaContentHolder.Media.getDefaultInstance();
        return this;
      }
    }
    
    static {
      serializers.protobuf.MediaContentHolder.getDescriptor();
    }
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_serializers_protobuf_Image_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serializers_protobuf_Image_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_serializers_protobuf_Media_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serializers_protobuf_Media_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_serializers_protobuf_MediaContent_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_serializers_protobuf_MediaContent_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String descriptorData =
      "\n\013media.proto\022\024serializers.protobuf\"\220\001\n\005" +
      "Image\022\013\n\003uri\030\001 \002(\t\022\r\n\005title\030\002 \001(\t\022\r\n\005wid" +
      "th\030\003 \001(\005\022\016\n\006height\030\004 \001(\005\022.\n\004size\030\005 \001(\0162 " +
      ".serializers.protobuf.Image.Size\"\034\n\004Size" +
      "\022\t\n\005SMALL\020\000\022\t\n\005LARGE\020\001\"\371\001\n\005Media\022\013\n\003uri\030" +
      "\001 \002(\t\022\r\n\005title\030\002 \001(\t\022\r\n\005width\030\003 \001(\005\022\016\n\006h" +
      "eight\030\004 \001(\005\022\016\n\006format\030\005 \001(\t\022\020\n\010duration\030" +
      "\006 \001(\003\022\014\n\004size\030\007 \001(\003\022\017\n\007bitrate\030\010 \001(\005\022\016\n\006" +
      "person\030\t \003(\t\0222\n\006player\030\n \001(\0162\".serialize" +
      "rs.protobuf.Media.Player\022\021\n\tcopyright\030\013 " +
      "\001(\t\"\035\n\006Player\022\010\n\004JAVA\020\000\022\t\n\005FLASH\020\000\"f\n\014Me" +
      "diaContent\022*\n\005image\030\001 \003(\0132\033.serializers." +
      "protobuf.Image\022*\n\005media\030\002 \001(\0132\033.serializ" +
      "ers.protobuf.MediaB*\n\024serializers.protob" +
      "ufB\022MediaContentHolder";
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_serializers_protobuf_Image_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_serializers_protobuf_Image_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_serializers_protobuf_Image_descriptor,
              new java.lang.String[] { "Uri", "Title", "Width", "Height", "Size", },
              serializers.protobuf.MediaContentHolder.Image.class,
              serializers.protobuf.MediaContentHolder.Image.Builder.class);
          internal_static_serializers_protobuf_Media_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_serializers_protobuf_Media_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_serializers_protobuf_Media_descriptor,
              new java.lang.String[] { "Uri", "Title", "Width", "Height", "Format", "Duration", "Size", "Bitrate", "Person", "Player", "Copyright", },
              serializers.protobuf.MediaContentHolder.Media.class,
              serializers.protobuf.MediaContentHolder.Media.Builder.class);
          internal_static_serializers_protobuf_MediaContent_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_serializers_protobuf_MediaContent_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_serializers_protobuf_MediaContent_descriptor,
              new java.lang.String[] { "Image", "Media", },
              serializers.protobuf.MediaContentHolder.MediaContent.class,
              serializers.protobuf.MediaContentHolder.MediaContent.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
}
