#! /usr/bin/env bash
set -e

path_sep=":"
case "`uname`" in
	CYGWIN*) path_sep=";" ;;
esac

cp=build/bytecode/main$path_sep$(cat build/gen-cp)$path_sep$(cat build/lib-cp)
exec java -Xmx256m -server -cp "$cp" serializers.BenchmarkRunner "$@"
