/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package serializers.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;
public enum Size implements TEnum{
    SMALL(1),
    LARGE(2);

  private static final Map<Integer, Size> BY_VALUE = new HashMap<Integer,Size>() {{
    for(Size val : Size.values()) {
      put(val.getValue(), val);
    }
  }};

  private final int value;

  private Size(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Size findByValue(int value) { 
    return BY_VALUE.get(value);
  }
}
