// automatically generated by the FlatBuffers compiler, do not modify

package serializers.flatbuffers.media;

public final class Player {
  private Player() { }
  public static final byte JAVA = 0;
  public static final byte FLASH = 1;

  public static final String[] names = { "JAVA", "FLASH", };

  public static String name(int e) { return names[e]; }
}

